name: Test mahotas-imread

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - '3.8'
          - '3.9'
          - '3.10'
          - '3.11'
          - '3.12'
        numpy-version:
          - '1.19'
          - '1.20'
          - '1.21'
          - '1.22'
          - '1.23'
          - '1.24'
          - '1.25'
          - '1.26'
          - '2.0'
        exclude:
            # 3.8 is too old for NumPy 1.25+
            - python-version: '3.8'
              numpy-version: '1.25'
            - python-version: '3.8'
              numpy-version: '1.26'
            - python-version: '3.8'
              numpy-version: '2.0'


            # NumPy 1.19 is not available on 3.7-9
            - python-version: '3.8'
              numpy-version: '1.19'
            - python-version: '3.9'
              numpy-version: '1.19'


            # NumPy <1.21 are too old for Python 3.10
            - python-version: '3.10'
              numpy-version: '1.19'
            - python-version: '3.10'
              numpy-version: '1.20'


            # NumPy <1.23 are too old for Python 3.11
            - python-version: '3.11'
              numpy-version: '1.19'
            - python-version: '3.11'
              numpy-version: '1.20'
            - python-version: '3.11'
              numpy-version: '1.21'
            - python-version: '3.11'
              numpy-version: '1.22'

            # NumPy <=1.25 are too old for Python 3.12
            - python-version: '3.12'
              numpy-version: '1.19'
            - python-version: '3.12'
              numpy-version: '1.20'
            - python-version: '3.12'
              numpy-version: '1.21'
            - python-version: '3.12'
              numpy-version: '1.22'
            - python-version: '3.12'
              numpy-version: '1.23'
            - python-version: '3.12'
              numpy-version: '1.24'
            - python-version: '3.12'
              numpy-version: '1.25'

    steps:
    - uses: actions/checkout@v4
    - uses: mamba-org/setup-micromamba@v1
      with:
        cache-environment: true
        cache-downloads: false
        environment-name: imread_test_env
        create-args: python=${{ matrix.python-version }} numpy=${{ matrix.numpy-version }}

    - name: Install dependencies
      shell: bash -l {0}
      run: |
        micromamba install --name imread_test_env python=${{ matrix.python-version }} numpy=${{ matrix.numpy-version }}
        micromamba install --quiet --yes -n imread_test_env jpeg libpng libwebp libtiff gcc_linux-64 gxx_linux-64 coveralls pytest
    - name: Build
      shell: bash -l {0}
      run: |
         make debug
    - name: Test with pytest
      shell: bash -l {0}
      run: |
         python -m pytest -v
